name: Fetch Data
on:
  schedule:
    - cron:  '0 1-23/4 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Fetch Data
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Script
        run: |
          pip install -r requirements.txt
          python parsedata.py >> log.txt
      - name: Commit Report
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -am "Automated Data Update"
          git push
